#????
server:
  port: 80
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true


# mybatis??
#mybatis.mapper-locations=classpath:/mapper/*.xml
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pittest?useSSL=false&useServerPrepStmts=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
#mybatis.configuration.map-underscore-to-camel-case=true
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


